In [24]:
import numpy as np

In [ ]:
# Create vector
data = np.arange(1,10)
vector1,vector2,vector3 = data.reshape(3,3)
print("vector1:", vector1)
print("vector2:", vector2)
print("vector3:", vector3)

vector1: [1 2 3]
vector2: [4 5 6]
vector3: [7 8 9]


In [ ]:
# Create vector
data = np.arange(1,10)
vector1 , vector2 , vector3 = np.split(data,3)
print("vector1:", vector1)
print("vector2:", vector2)
print("vector3:", vector3)

vector1: [1 2 3]
vector2: [4 5 6]
vector3: [7 8 9]


In [ ]:
# Create 3 matrices
mat_data = np.arange(1,13).reshape(3,2,2)

matrix1,matrix2,matrix3 = mat_data
print("matrix1:",matrix1)
print("matrix2:",matrix2)
print("matrix3:",matrix3)

matrix1: [[1 2]
 [3 4]]
matrix2: [[5 6]
 [7 8]]
matrix3: [[ 9 10]
 [11 12]]


In [ ]:
# Print shapes
print(vector1.shape)
print(vector2.shape)
print(vector3.shape)


(3,)
(3,)
(3,)


In [ ]:
# Print shapes
print(matrix1.shape)
print(matrix2.shape)
print(matrix3.shape)

(2, 2)
(2, 2)
(2, 2)


In [ ]:
# Matrix addition
matrix1 + matrix2

array([[ 6,  8],
       [10, 12]])

In [33]:
# Scalar multiplication
matrix3 * 3

array([[27, 30],
       [33, 36]])

In [39]:
# Dot product of
np.dot(vector1,vector2)

np.int64(32)

In [38]:
# Matrix multiplication 
matrix1 @ matrix2

array([[19, 22],
       [43, 50]])

In [ ]:
# Perform matrix multiplication manually — using a loop
matrix1 = [[1,2],
[3,4]]
matrix2 = [[5,6],
[7,8]]

# initialy resultant matrix will be a zero matrix with same dimentions
result = [[0,0],
[0,0]]

for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            result[i][j] += matrix1[i][k]*matrix2[k][j]
for row in result:
    print(row)

[19, 22]
[43, 50]


In [46]:
len(matrix2)

2