Day - 1

In [4]:
import numpy as np

In [5]:
# Create vector
data = np.arange(1,10)
vector1,vector2,vector3 = data.reshape(3,3)
print("vector1:", vector1)
print("vector2:", vector2)
print("vector3:", vector3)

vector1: [1 2 3]
vector2: [4 5 6]
vector3: [7 8 9]


In [6]:
# Create vector
data = np.arange(1,10)
vector1 , vector2 , vector3 = np.split(data,3)
print("vector1:", vector1)
print("vector2:", vector2)
print("vector3:", vector3)

vector1: [1 2 3]
vector2: [4 5 6]
vector3: [7 8 9]


In [7]:
# Create 3 matrices
mat_data = np.arange(1,13).reshape(3,2,2)

matrix1,matrix2,matrix3 = mat_data
print("matrix1:",matrix1)
print("matrix2:",matrix2)
print("matrix3:",matrix3)

matrix1: [[1 2]
 [3 4]]
matrix2: [[5 6]
 [7 8]]
matrix3: [[ 9 10]
 [11 12]]


In [8]:
# Print shapes
print(vector1.shape)
print(vector2.shape)
print(vector3.shape)


(3,)
(3,)
(3,)


In [9]:
# Print shapes
print(matrix1.shape)
print(matrix2.shape)
print(matrix3.shape)

(2, 2)
(2, 2)
(2, 2)


In [10]:
# Matrix addition
matrix1 + matrix2

array([[ 6,  8],
       [10, 12]])

In [11]:
# Scalar multiplication
matrix3 * 3

array([[27, 30],
       [33, 36]])

In [12]:
# Dot product of
np.dot(vector1,vector2)

np.int64(32)

In [13]:
# Matrix multiplication 
matrix1 @ matrix2

array([[19, 22],
       [43, 50]])

In [14]:
# Perform matrix multiplication manually — using a loop
matrix1 = [[1,2],
[3,4]]
matrix2 = [[5,6],
[7,8]]

# initialy resultant matrix will be a zero matrix with same dimentions
result = [[0,0],
[0,0]]

for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            result[i][j] += matrix1[i][k]*matrix2[k][j]
for row in result:
    print(row)

[19, 22]
[43, 50]


In [15]:
len(matrix2)

2

Day - 2

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
print("shape of matrix befor transpose:", matrix.shape)
matrix = matrix.T
print("shape of matrix after transpose:" , matrix.shape)

shape of matrix befor transpose: (2, 3)
shape of matrix after transpose: (3, 2)


In [29]:
matrix1 = np.array([[1,2,3],[1,2,3]])
matrix2 = np.array([[4,5],[4,5],[4,5]])
result = matrix1 @ matrix2
print(result.shape)
result2 = matrix2 @ matrix1
print(result2.shape)

(2, 2)
(3, 3)


In [34]:
# Example of error of mismatch
matrix1 = np.array([[1,2,3],[1,2,3]])
matrix2 = np.array([[4,5,3],[4,5,3],[4,5,3]])
result = matrix1 @ matrix2
print(result.shape)
result2 = matrix2 @ matrix1
print(result2.shape)

(2, 3)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [52]:
matrix = np.array([[3,4,5],[6,7,8],[2,5,9]])
determinant =np.linalg.det(matrix)
print(determinant)
inverse = np.linalg.inv(matrix)
print(inverse)


-2.9999999999999996
[[-7.66666667  3.66666667  1.        ]
 [12.66666667 -5.66666667 -2.        ]
 [-5.33333333  2.33333333  1.        ]]


In [53]:
print(matrix @ inverse)


[[ 1.00000000e+00  8.88178420e-16 -2.22044605e-16]
 [-7.10542736e-15  1.00000000e+00 -8.88178420e-16]
 [-4.44089210e-15  8.88178420e-16  1.00000000e+00]]
